#ifndef __MSG_H
#define __MSG_H

enum noti_message {
    BLE_PERIPHERAL_DISCONNECTED=1,
    BLE_PERIPHERAL_CONNECTED,
    BLE_PERIPHERAL_UNSUBSCRIBED,
    BLE_PERIPHERAL_SUBSCRIBED,
    BLE_PERIPHERAL_SCANNING,
    BLE_PERIPHERAL_FOUND,
    SD_CARD_ERROR
};

#endif //__MSG_H
